services:
  wordpress:
    image: wordpress:6.9
    env_file: .env
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'ALLOW_UNFILTERED_UPLOADS', true );

    networks:
      - appworld

  mysql:
    image: mysql:8.0
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - appworld

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    env_file: .env
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - appworld

volumes:
  db_data: {}
  wp_data: {}

networks:
  appworld:
